name: Main
on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.6", "2.7", "3.0", "3.1"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Generate lockfile
        run: bundle lock

      - name: Run Setup
        run: ./bin/setup

      - name: Run tests
        env:
          BLINKA_JSON: true
        run: bundle exec rake test

      - name: Build and install gem
        run: gem build blinka_reporter.gemspec && gem install blinka-reporter-*.gem

      - name: Report to Blinka
        env:
          BLINKA_REPOSITORY: davidwessman/blinka_reporter
          BLINKA_TEAM_ID: ${{ secrets.BLINKA_TEAM_ID }}
          BLINKA_TEAM_SECRET: ${{ secrets.BLINKA_TEAM_SECRET }}
          BLINKA_TAG: ${{ matrix.ruby }}
        run: blinka_reporter --blinka --tap --path ./blinka_results.json
