name: Main
on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7", "3.0", "3.1", "3.2"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Generate lockfile
        run: bundle lock

      - name: Run Setup
        run: ./bin/setup

      - name: Run tests
        env:
          BLINKA_PATH: ./results.json
        run: bundle exec rake test

      - name: Build and install gem
        if: always()
        run: gem build blinka_reporter.gemspec && gem install blinka-reporter-*.gem

      - name: Report TAP-results
        if: always()
        run: |
          blinka_reporter --tap --path ./results.json

      - name: Export Blinka-metadata
        if: always()
        run: |
          echo "${{ matrix.ruby }}" > ./blinka_tag

      - name: Blinka - Archive
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: blinka-${{ strategy.job-index }}
          path: |
            ./results.json
            ./blinka_tag
