name: Main
on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby: ["2.6.6", "2.7.2", "3.0.0"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Generate lockfile
        run: bundle lock

      - name: Run Setup
        run: ./bin/setup

      - name: Run tests
        env:
          BLINKA_JSON: true
          BLINKA_REPORT: true
          BLINKA_REPOSITORY: davidwessman/blinka_reporter
          BLINKA_TAP: true
          BLINKA_TEAM_ID: ${{ secrets.BLINKA_TEAM_ID }}
          BLINKA_TEAM_SECRET: ${{ secrets.BLINKA_TEAM_SECRET }}
          BLINKA_TAG: ${{ matrix.ruby }}
        run: bundle exec rake test

      - name: Is it main?
        run: |
          echo $GITHUB_REF
