name: Main
on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Generate lockfile
        run: bundle lock

      - name: Run Setup
        run: ./bin/setup

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('Gemfile.lock') }}

      - name: Run tests
        env:
          BLINKA_JSON: true
          BLINKA_REPORT: true
          BLINKA_REPOSITORY: davidwessman/blinka_reporter
          BLINKA_TAP: true
          BLINKA_TEAM_ID: ${{ secrets.BLINKA_TEAM_ID }}
          BLINKA_TEAM_SECRET: ${{ secrets.BLINKA_TEAM_SECRET }}
        run: bundle exec rake test
