name: Main
on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.6", "2.7", "3.0", "3.1"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Generate lockfile
        run: bundle lock

      - name: Run Setup
        run: ./bin/setup

      - name: Run tests
        env:
          BLINKA_PATH: ./results.json
        run: bundle exec rake test

      - name: Build and install gem
        if: always()
        run: gem build blinka_reporter.gemspec && gem install blinka-reporter-*.gem

      - name: Report to Blinka
        if: always()
        run: |
          blinka_reporter \
          --blinka \
          --tap \
          --path ./results.json \
          --repository davidwessman/blinka_reporter \
          --tag ${{ matrix.ruby }} \
          --team-id ${{ secrets.BLINKA_TEAM_ID }} \
          --team-secret ${{ secrets.BLINKA_TEAM_SECRET }}
